sudo: false
language: node_js
node_js:
- 6
- 7
- 8
after_success: npm run coverage
addons:
  apt: 
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8
        - libimage-exiftool-perl
