sudo: false
language: node_js
node_js:
- 12
- 10
- 8
after_success: npm run coverage
env:
  - CXX=g++-4.8
addons:
  apt: 
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8
        - libimage-exiftool-perl
