sudo: false
language: node_js
node_js:
- 6
- 7
- 8
after_success: npm run coverage
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
addons:
  apt: 
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8
        - libimage-exiftool-perl
